networks:
  personal-network:
    external: true
services:
  spring-boot-template-service:
    build: 
      context: ./source/spring-boot-template
      dockerfile: dev.Dockerfile
      args:
        userID: ${userID:-1000}
        groupID: ${groupID:-1000}
    volumes:
      - ./:/app/
      - ~/.gradle:/tmp/gradle_user_home
    working_dir: /app/source/spring-boot-template
    ports:
      - "8080:8080"
    command: [ "sh", "./run.sh" ]
    user: ${userID:-1000}:${groupID:-1000}
    networks:
      - personal-network
    hostname: spring-boot-template-service
    container_name: spring-boot-tempate-service