apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-starter
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        octopusexport: OctopusExport
    spec:
      containers:
        - name: spring-boot-starter
          image: 'gcr.io/spring-boot-starter-320707/spring-boot-starter:v1'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-starter-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    octopusexport: OctopusExport
  type: LoadBalancer