apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels" . | indent 4 }}
  annotations:
    {{- include "annotations" . | indent 4 }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.surge }}
      maxUnavailable: {{ .Values.strategy.unavailable }}
  template:
    metadata:
      labels:
        {{- include "labels" . | indent 4 }}
      annotations:
        {{- include "annotations" . | indent 4 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "image" . }}
          ports:
            - protocol: TCP
              containerPort: {{ .Values.container.port }}
          resources:
            requests:
              cpu: {{ .Values.container.resources.requests.cpu }}
              memory: {{ .Values.container.resources.requests.memory }}
            limits:
              cpu: {{ .Values.container.resources.limits.cpu }}
              memory: {{ .Values.container.resources.limits.memory }}
