apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "labels" . | indent 2 }}
  annotations: {{- include "annotations" . | indent 2 }}
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "image.secret" . }}