apiVersion: v1
kind: Service
metadata:
  labels: {{- include "labels" . | indent 4 }}
  annotations: {{- include "annotations" . | indent 4 }}
  name: {{ .Chart.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
